### ISSUE TITLE
missing unit test for checking that your package loads correctly

### ISSUE THREAD

**Issue by jennmcguire** [phys201/fitness_mcmc#26]
You should have a unit test that tests if your package is loading correctly. The python packaging tutorial (https://python-packaging.readthedocs.io/en/latest/testing.html) has an example.

**Comment by Lyosef789** [comment]
Wouldn't the code in 'test_io' or 'test model' tests suffice?

**Comment by jennmcguire** [comment]
In effect yes, but they're not testing the package loading directly. You should make a less specific test that ensures the package loading is correct without testing specific functions. For example, you could test if one of your functions returned the right data type (pymc3 model, pandas dataframe, etc). This would test that you package is loading correctly without being dependent on the function working exactly as designed. You could then use separate tests to see if the functions are working as intended.

**Comment by pavelzhelnin** [comment]
Done with this commit: 3ec9747. Tested if the load data function returns a pandas data frame.

**Comment by Lyosef789** [comment]
Also, please see 'test_func', it tests if the sample_lineages function returns a numpy array
