### ISSUE TITLE
more tests! 

### ISSUE THREAD

**Issue by aspitzig0** [phys201/fitness_mcmc#33]
Good to see the test for the normalization function! Need to add more tests for the other functions defined in that .py notebook. (Not an 'issue', but clever implementation of Class in that notebook as well - looks useful!)

**Comment by talha1369** [comment]
Good to also see that the PEP 8 guidelines have been followed for Class in fitness_mcmc.py as well!

**Comment by pavelzhelnin** [comment]
Added more tests in this commit: 3ec9747
