### ISSUE TITLE
test for preventing user errors in reporting counts!

### ISSUE THREAD

**Issue by talha1369** [phys201/fitness_mcmc#35]
I think you can benefit from a test ensuring the user provides the right data and avoid any errors. One way to check this would be to compare the counts (the number of each genotype alive), which would be always <= counts reported for the previous generation. For example, counts for generation 5 are always >= counts for generation 45. If a user incorrectly provides counts which do not fit this criterion, your package can raise an exception, and similarly, you can implement an exception for NAN.

**Comment by pavelzhelnin** [comment]
Thanks Talha, I think this has been addressed in latest commit 3ec9747.
