### ISSUE TITLE
Implement distribution of fitnesses

### ISSUE THREAD

**Issue by vnmanoharan** [phys201/fitness_mcmc#37]
We've discussed this but I'm filing it as an issue as a reminder.  You can implement a hierarchical model to account for the distribution over the s_i.  To do this, specify that s_i ~ Normal(mu, sigma) and then specify hyperpriors over the mu and sigma.

**Comment by pavelzhelnin** [comment]
Will try to do soon. Didn't have the time to complete before this deadline.
